# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Install Node
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Step 2: Install dependencies
- script: |
    npm ci
  displayName: 'Install dependencies'

# Step 3: Install Playwright browsers
- script: |
    npx playwright install --with-deps
  displayName: 'Install Playwright browsers'

# Step 4: Run Playwright tests
- script: |
    npx playwright test
  displayName: 'Run Playwright tests'

  # Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/results.xml'

    - script: |
    npx playwright show-report
  displayName: 'Generate HTML Report'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'playwright-report'
    artifactName: 'playwright-report'
    failTaskOnFailedTests: true
  condition: always()
